---
sa_items: []

sa_languages: []

sa_feed_items_importation_types: []

sa_ws_types: []

sa_item_categories: []

sa_allowed_free_user_creation: "false"
sa_automatic_private_workspace: "true"

sa_application_name: ThinkDRY BLANK Application
sa_application_url: http://blank.thinkdry.com
sa_favicon_url: /config_files/favicon.ico
sa_logo_url: /config_files/logo.jpg
sa_per_page_default: 10
