DEFAULTS: &DEFAULTS
  adapter: mysql
  encoding: utf8
  host: localhost
  username: thinkdry
  password: AK47freedom
  socket: /var/run/mysqld/mysqld.sock

development:
  database: blank_dev
  <<: *DEFAULTS
  
test:
  database: blank_test
  <<: *DEFAULTS
  
production:
  database: blank_prod
  <<: *DEFAULTS
